=== Ales-Litvin/StudyJava/src/main/java/by/bsu/xml/tasks/oldcard/data/old_cards.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT old_cards (old_card)+>
        <!ELEMENT old_card (country, year, author, valuable)>
        <!ATTLIST old_card
                theme CDATA #REQUIRED
                typeContent CDATA #REQUIRED>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT valuable (#PCDATA)>

=== Ales-Litvin/StudyJava/src/main/java/by/bsu/xml/tasks/oldcard/data/old_cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE old_cards SYSTEM "old_cards.dtd">

<old_cards>
    <old_card theme="cityscape" typeContent="congratulation">
        <country>Belarus</country>
        <year>2020</year>
        <author>No name</author>
        <valuable>history</valuable>
    </old_card>

    <old_card theme="nature" typeContent="advertising">
        <country>Poland</country>
        <year>2021</year>
        <author>No name</author>
        <valuable>collecting</valuable>
    </old_card>

    <old_card theme="people" typeContent="usual">
        <country>Brazil</country>
        <year>2019</year>
        <author>Ales</author>
        <valuable>thematic</valuable>
    </old_card>

</old_cards>
